---
title: "Statistical Computing 2022: Introduction to Causal Discovery"
subtitle: "Causal Discovery"
author: "V Didelez, C W Bang"
date: "July 25 2022"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Causal Discovery}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}  
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      fig.width = 6, 
                      message = FALSE, 
                      warning = FALSE, 
                      cache = TRUE, 
                      eval = TRUE)

options(rmarkdown.html_vignette.check_title = FALSE)
```


```{r libraries}
#library(IntroductionCausalDiscovery)
library(tidyverse)
library(pcalg)
```


# Descriptive statistics

```{r read_tcga}
data(tcgas)

dim(tcgas)
```


```{r head_tcga}
head(tcgas)
```


```{r plot_tcga}
plot(tcgas, cex = 0.3)
```


```{r hist_tcga}
tcgas %>% 
  gather() %>% 
  ggplot(aes(x = value)) +
  geom_histogram(col = "black", fill = "white") + 
  theme_light() +
  facet_wrap(~ key)
```



# PC-algorithm

```{r fitpc_tcga}
pcfit05 <- pc(
  suffStat = list(C = cor(tcgas), n = dim(tcgas)[1]), # correlation matrix and the number of observations
  indepTest = gaussCItest, # our choice of independence test
  alpha = 0.05, # our choice of "significance level"
  labels = colnames(tcgas), # variable names
  maj.rule = T, solve.confl = T, u2pd = "relaxed"
)
```

We get 12 edges regardless of the level of alpha:

```{r fitalpha_tcga}
pcfit01 <- pc(
             suffStat = list(C = cor(tcgas), n = dim(tcgas)[1]),
            indepTest = gaussCItest,
                alpha = 0.01,
               labels = colnames(tcgas),
             maj.rule = T, solve.confl = T, u2pd = "relaxed"
             )
pcfit10 <- pc(
             suffStat = list(C = cor(tcgas), n = dim(tcgas)[1]),
            indepTest = gaussCItest,
                alpha = 0.1,
               labels = colnames(tcgas),
             maj.rule = T, solve.confl = T, u2pd = "relaxed"
            )


plot(pcfit01@graph, main = "alpha = 1%")
plot(pcfit05@graph, main = "alpha = 5%")
plot(pcfit10@graph, main = "alpha = 10%")
```

# FCI-algorithm

```{r fitfci}
fcifit <- fci(
  suffStat = list(C = cor(tcgas), n = dim(tcgas)[1]),
  indepTest = gaussCItest,
  alpha = 0.05,
  labels = colnames(tcgas),
  maj.rule = TRUE,
  selectionBias = FALSE
)

plot(fcifit, main = "alpha = 5%")
```


With alpha = 0.1 we get 12 edges as for the PC-algorithm:

```{r fitfci2}
fcifit <- fci(
  suffStat = list(C = cor(tcgas), n = dim(tcgas)[1]),
  indepTest = gaussCItest,
  alpha = 0.1,
  labels = colnames(tcgas),
  maj.rule = TRUE,
  selectionBias = FALSE
)

plot(fcifit, main = "alpha = 10%")
```


# GES-algorithm

```{r fitges_tcga}
gesfit <- ges(new("GaussL0penObsScore", tcgas))

plot(gesfit$essgraph)
```



# LiNGAM

```{r fitlingam_tcga}
lingamfit <- lingam(tcgas)
```


```{r lingamfct}
lingam2graph <- function(fit,data){
  
  amat <- t(fit$Bpruned!=0)
  colnames(amat) <- colnames(data)
  
  output <- as(amat, "graphNEL")
  
  return(output)
}
```


```{r graphlingam_tcga}
lingamgraph <- lingam2graph(fit = lingamfit, # fitted object
                            data = tcgas) # data used to fit the object

plot(lingamgraph)
```



# Kernel independence tests

```{r kpcfit, eval=FALSE}
library(kpcalg)

pcfit_kernel05 <- pc(suffStat = list(data = tcgas, ic.method = "dcc.perm"),
                     indepTest = kernelCItest,
                     alpha = 0.05,
                     labels = colnames(tcgas),
                     maj.rule = TRUE, solve.confl = TRUE, u2pd = "relaxed"
                     )
pcfit_kernel10 <- pc(suffStat = list(data = tcgas, ic.method = "dcc.perm"),
                     indepTest = kernelCItest,
                     alpha = 0.1,
                     labels = colnames(tcgas),
                     maj.rule = TRUE, solve.confl = TRUE, u2pd = "relaxed")
}
```


```{r kpcfitload, echo=FALSE}
load('kernel.RData')
```
```{r}
par(mfrow = c(1,2))
plot(pcfit_kernel05, main = "alpha = 5%")
plot(pcfit_kernel10, main = "alpha = 10%")
```

With alpha = 0.16 we get 12 edges:

```{r fitkernel2}
pcfit_kernel16 <- pc(suffStat = list(data = tcgas, ic.method = "dcc.perm"),
                     indepTest = kernelCItest,
                     alpha = 0.16,
                     labels = colnames(tcgas),
                     maj.rule = TRUE, solve.confl = TRUE, u2pd = "relaxed")
```

```{r, echo = FALSE, eval = FALSE}
#save(pcfit_kernel05, pcfit_kernel10, pcfit_kernel16, file = 'kernel.RData')
```

```{r plotkernel2}
par(mfrow = c(1,1))
plot(pcfit_kernel16, main = "alpha = 16%")
```



# Generalised Covariance Measure

```{r gcm_wrapper, warning=FALSE}
library(GeneralisedCovarianceMeasure)

use_gcm <- function(x, y, S, suffStat){
  
  a <- as.matrix(suffStat$data)[,x]
  b <- as.matrix(suffStat$data)[,y]
  c <- as.matrix(suffStat$data)[,S]
  
  test <- gcm.test(a, b, c, alpha = suffStat$alpha)
  p_value <- test[[1]]
  
  return(p_value)
} 
```


```{r pcfit_gcm, eval = FALSE}
pcfit_gcm05 <- pc(suffStat = list(data = tcgas, alpha = 0.05),
                  indepTest = use_gcm,
                  alpha = 0.05,
                  labels = colnames(tcgas),
                  maj.rule = TRUE, solve.confl = TRUE, u2pd = "relaxed"
                  )
pcfit_gcm10 <- pc(suffStat = list(data = tcgas, alpha = 0.1),
                  indepTest = use_gcm,
                  alpha = 0.1,
                  labels = colnames(tcgas),
                  maj.rule = TRUE, solve.confl = TRUE, u2pd = "relaxed"
                  )
```

```{r load_gcm, echo = FALSE}
#save(pcfit_gcm05, pcfit_gcm10, file = 'gcm.RData')
load('gcm.RData')
```

For both levels of alpha we get 12 edges:

```{r plot_gcm}
par(mfrow = c(1,2))
plot(pcfit_gcm05, main = "alpha = 5%")
plot(pcfit_gcm10, main = "alpha = 10%")
```


# Discrete data
```{r disICfunc}
data(tcgadisc)

disCItest_mod <- function(x, y, S, suffStat){
  if (is.data.frame(dm <- suffStat$dm)) 
        dm <- data.matrix(dm)
  else stopifnot(is.matrix(dm))
  nlev <- suffStat$nlev
  adaptDF <- suffStat$adaptDF
  gSquareDis(x = x, y = y, S = S, dm = dm, nlev = nlev, adaptDF = adaptDF,
             verbose = FALSE, n.min = -1)
}
 
pcfit_d05 <- pc(suffStat = list(dm = tcgadisc, adaptDF = F),
                indepTest = disCItest_mod,
                alpha = 0.05,
                labels = colnames(tcgadisc),
                maj.rule = T, solve.confl = T, u2pd = "relaxed"
                )
pcfit_d10 <- pc(suffStat = list(dm = tcgadisc, adaptDF = F),
                indepTest = disCItest_mod,
                alpha = 0.1,
                labels = colnames(tcgadisc),
                maj.rule = T, solve.confl = T, u2pd = "relaxed"
                )
```


```{r plot_dis}
par(mfrow = c(1,2))
plot(pcfit_d05@graph, main = "alpha = 5%")
plot(pcfit_d10@graph, main = "alpha = 10%")
```

With alpha = 0.36 we get 12 edges:

```{r fit_dis2}
pcfit_d36 <- pc(suffStat = list(dm = tcgadisc, adaptDF = F),
                indepTest = disCItest_mod,
                alpha = 0.36,
                labels = colnames(tcgadisc),
                maj.rule = T, solve.confl = T, u2pd = "relaxed"
                )
```


```{r plot_dis2}
par(mfrow = c(1,1))
plot(pcfit_d10@graph, main = "alpha = 36%")
```

# Comparison


```{r libgrbase}
library(gRbase)
```


```{r pa}
parents("HMGA2", as(gesfit$essgraph, "graphNEL"))
```


```{r ch}
children("HMGA2", as(gesfit$essgraph, "graphNEL"))
```


```{r an}
ancestors("HMGA2", as(gesfit$essgraph, "graphNEL"))
```


```{r possan}
possAn(t(as(as(gesfit$essgraph, "graphNEL"), "Matrix")), # the graph has to be specified as a matrix
       x = 4, # indicates the position of the variables of interest
       type = "cpdag" # type of graph
       )
```


```{r names_possan}
colnames(tcgas)[c(1,4,5,6,7)]
```


```{r possde}
possDe(t(as(as(gesfit$essgraph, "graphNEL"), "matrix")), 
       x = 4, 
       type = "cpdag" 
       )
```

```{r names_possde}
colnames(tcgas)[c(2,3,4,8)]
```


# IDA algorithm

```{r lm1_fcga}
summary(lm(CDK6 ~ HMGA2 + BAX + CDKN2A + CDKN1A + MDM2 + SERPINE1 + THBS1, data = tcgas))$coefficients
```


```{r print_names}
names(tcgas)
```


```{r ida_local}
ida(x.pos = 4, # position of HMGA2 in the dataset 
    y.pos = 8, # position of CDK6 in the dataset
    cov(tcgas), # covariance matrix of the dataset
    graphEst = as(gesfit$essgraph,"graphNEL"), # estimated graph
    method = "local", # type of adjustment set
    type = "cpdag", # type of the estimated graph
    verbose = TRUE
      )
```

```{r, echo = F}
ida(x.pos = 4, # position of HMGA2 in the dataset 
    y.pos = 8, # position of CDK6 in the dataset
    cov(tcgas), # covariance matrix of the dataset
    graphEst = as(gesfit$essgraph,"graphNEL"), # estimated graph
    method = "local", # type of adjustment set
    type = "cpdag", # type of the estimated graph
    verbose = TRUE
      ) -> idaest1
```


```{r lm2_fcga}
summary(lm(CDK6 ~ HMGA2 + SERPINE1 + THBS1, data = tcgas))$coefficients
```


```{r ida_optimal}
ida(x.pos = 4,
    y.pos = 8,
    cov(tcgas),
    graphEst = as(gesfit$essgraph,"graphNEL"),
    method = "optimal",
    type = "cpdag",
    verbose = TRUE
      )
```


```{r lm3_fcga}
summary(lm(CDK6 ~ HMGA2 + SERPINE1 + THBS1 + MDM2, data = tcgas))$coefficients
```


```{r ida_alt}
ida(x.pos = 5,
    y.pos = 8,
    cov(tcgas),
    graphEst = as(gesfit$essgraph,"graphNEL"),
    method = "local",
    type = "cpdag",
    verbose = T
      )
```